/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task6_dev;

import task6_dev.DataBase.DataBase;
import task6_dev.DbServises.DatabaseInitService;

public class App {



    public static void main(String[] args) {
        DataBase db = DataBase.getInstance();
        new DatabaseInitService().initDb(db);
    }
}
